### ISSUE TITLE
关于 Markdown 语法中行内代码的处理

### ISSUE THREAD

**Issue by miranquil** [vinta/pangu.py#12]
如题，现在很多文章都将Markdown 中行内代码“ ` ”语法作为强调句等功能使用，不仅限于代码，因此行内代码块中第一个字符是中文的情况也不算少见。在这种情况下 pangu 也会自动添加空格，如下：

原文：
这是`行内代码`的例子。
pangu 生成的格式：
这是 `行内代码` 的例子。

个人觉得不太妥，请问这种情况下是否应该出现空格？

**Comment by DeppWang** [comment]
个人感觉这种加上空格更好，更美观，有点突出显示的感觉

**Comment by yorushika** [comment]
> 个人感觉这种加上空格更好，更美观，有点突出显示的感觉

但这不是 pangu 的本意

**Comment by DeppWang** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    你可以按你自己的需求改一改源码，最后可以提交 pull request
    
        
            
        
    
    
          
        
            
    
        font{
            line-height: 1.6;
        }
    
公众号：DeppWang个人博客：https://depp.wang个人主页：https://github.com/deppwang

    

        
    
     
    

    在2019年09月6日 17:55，Wisteria<notifications@github.com> 写道： 




个人感觉这种加上空格更好，更美观，有点突出显示的感觉



但这不是 pangu 的本意

**Comment by aboutmydreams** [comment]
有空格是更好的
