### ISSUE TITLE
会把代码大括号产生的换行吃掉

### ISSUE THREAD

**Issue by xwartz** [vinta/pangu.py#5]
比如：

``` js
var fun = function(){
   console.log('xxx')
}
```

转换之后变成了

``` js
var fun = function(){console.log('xxx')}
```

**Comment by daoiqi** [comment]
```python
FIX_QUOTE_RE = re.compile(u(r'(["\'\(\[\{<\u201c]+)(\s*)(.+?)(\s*)(["\'\)\]\}>\u201d]+)'))

new_text = FIX_QUOTE_RE.sub(r'\1\3\5', new_text)
```

这个把空格全部给去除了。不知道是否合理

**Comment by vinta** [comment]
其實當初設計的時候就覺得不應該作用在程式碼上
只會用在一般的文本（自然語言）上
例如 https://github.com/vinta/pangu.js 會直接略過 `<code>` 和 `<pre>` 之類的區塊

不過應該是可以處理一下換行的問題
有沒有興趣發個 pull request 呢？

**Comment by daoiqi** [comment]
这些正则表达式，都是各个项目一致的，不知道要怎么个考虑。

另外对于markdown、rst这样的文本，应该就支持不太好了。

**Comment by eromoe** [comment]
我想问下，这个程序的目的是啥，为了让输出的文字看过去更好看？
除此之外还有什么可以应用的地方？

**Comment by vinta** [comment]
哈哈哈真的就是為了讓輸出的文字更好看，至少我當初開發的時候就只有這個理由

**Comment by vinta** [comment]
Won't fix. Also see https://github.com/vinta/pangu.js/issues/127
